import type { Icon } from "@phosphor-icons/react";
import {
  Airplane,
  Armchair,
  BookOpen,
  BookOpenText,
  Briefcase,
  Camera,
  Car,
  Cards,
  Cloud,
  Code,
  Compass,
  Crown,
  Cube,
  Folder,
  GraduationCap,
  GridFour,
  Heartbeat,
  ListChecks,
  MapTrifold,
  MusicNotes,
  Newspaper,
  PuzzlePiece,
  Question,
  Smiley,
  SoccerBall,
  Sword,
  Television,
  TextT,
  Users,
  UsersThree,
  Wallet,
  Wrench,
} from "@phosphor-icons/react/ssr";

/** Slug → icon across app/game taxonomies (shared slugs like sports resolve once). */
const CATEGORY_ICONS: Record<string, Icon> = {
  business: Briefcase,
  "developer-tools": Code,
  education: GraduationCap,
  entertainment: Television,
  finance: Wallet,
  "health-fitness": Heartbeat,
  lifestyle: Armchair,
  music: MusicNotes,
  navigation: MapTrifold,
  news: Newspaper,
  "photo-video": Camera,
  productivity: ListChecks,
  reference: BookOpen,
  social: Users,
  sports: SoccerBall,
  travel: Airplane,
  utilities: Wrench,
  weather: Cloud,
  action: Sword,
  adventure: Compass,
  board: GridFour,
  card: Cards,
  casual: Smiley,
  family: UsersThree,
  puzzle: PuzzlePiece,
  racing: Car,
  "role-playing": BookOpenText,
  simulation: Cube,
  strategy: Crown,
  trivia: Question,
  word: TextT,
};

/** Icon for a category slug (apps ∪ games). */
export function getCategoryIconBySlug(slug: string): Icon {
  return CATEGORY_ICONS[slug] ?? Folder;
}
